FROM node:23.3.0-slim

RUN apt update && \
    apt install -y docker.io     

# RUN groupadd -g 989 dockerhost || true && usermod -aG 989 node
RUN groupadd -g 118 dockerhost || true && usermod -aG 118 node
    
RUN npx playwright install-deps chromium

USER node

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .
RUN npm ci
# RUN npx playwright install chromium

EXPOSE 3000 

CMD [ "tail", "-f", "/dev/null" ]