FROM node:24.9.0-slim

RUN apt update && \
apt install -y curl gpg gnupg gpg-agent socat docker.io 

ARG DOCKER_GID=989
RUN groupadd -g ${DOCKER_GID} dockerhost || true && usermod -aG ${DOCKER_GID} node

RUN npx playwright install-deps chromium

USER node

WORKDIR /home/node/app

EXPOSE 3000 
