FROM node:23.3.0-slim

RUN apt update && \
    apt install -y curl gpg gnupg gpg-agent socat 

COPY .docker/start.sh /
RUN chmod +x start.sh

USER node

WORKDIR /home/node/app

EXPOSE 3000 

CMD ["/start.sh"]