services:
  sav:
    build:
      args:
        DOCKER_GROUP_ID: "989"
        USER_ID: "1000"
    volumes:
      # Configuration for using custom images with Testcontainers
      # - ~/.docker/config-read.json:/home/node/.docker/config.json:ro
    environment:
      E2E_BASE_URL: http://sav:3000
      BROWSER_WSS_ENDPOINT: ws://playwright:3001
